#!/bin/bash
srcr () {
  TARGET=$1
  if [[ -f ${TARGET} ]]; then
    source ${TARGET}
  fi
}
srcr ~/.vvrc
srcr ~/.vv/config
srcr ~/.config/vv/config

# Overrideable vars
: ${VV_NICENESS:="19"}
: ${VV_IO_NICENESS:="3"}
# change the PRE COMMAND
: ${VV_PRE:="/usr/bin/time -v nice -n${VV_NICENESS} ionice -c${VV_IO_NICENESS} "}
: ${VV_LIST_FILES:='/usr/share/sounds/gnome/default/alerts/string.ogg
  /usr/share/sounds/gnome/default/alerts/click.ogg
  /usr/share/sounds/oxygen/stereo/game-over-winner.ogg
  /usr/share/sounds/freedesktop/stereo/phone-incoming-call.oga
  /usr/share/sounds/Oxygen-Im-Sms.ogg
  '}

alertr () {
  if [ -z ${VV_PLAYER+x} ]; then 
    if command -v cvlc 2>&1 >/dev/null; then
      VV_PLAYER="cvlc --no-loop --no-repeat --play-and-exit"
    elif command -v ogg123 2>&1 >/dev/null; then
      VV_PLAYER=ogg123
    elif command -v mplayer 2>&1 >/dev/null; then
      VV_PLAYER=mplayer
      cvlc --no-loop --no-repeat --play-and-exit
    else
      echo 'WARN: no player found!'
    fi
  fi
  if [[ ${VV_PLAYER} == 'cvlc' ]]; then
    VV_LIST_FILES="/usr/share/sounds/alsa/Front_Center.wav 
    $VV_LIST_FILES"
  elif [[ ${VV_PLAYER} == 'mplayer' ]]; then
    VV_LIST_FILES="/usr/share/sounds/alsa/Front_Center.wav 
    $VV_LIST_FILES"
  elif [[ ${VV_PLAYER} == 'ogg123' ]]; then
    VV_LIST_FILES='/usr/share/sounds/oxygen/stereo/game-over-winner.ogg
    /usr/share/sounds/Oxygen-Im-Sms.ogg
    '
  fi
  if [ -z ${VV_PLAYFILE+x} ]; then 
    for i in ${VV_LIST_FILES}; do
      if [[ -f $i ]]; then
        VV_PLAYFILE=$i
      fi
    done
  fi
  if [ -z ${VV_PLAYER+x} ]; then 
    echo 'no player found, not beeping'
  elif [ -z ${VV_PLAYFILE+x} ]; then 
    echo 'no playerfile found, not beeping'
  else 
    ${VV_PLAYER} ${VV_PLAYFILE}
  fi
}

vvr () {
# this is a wrapper script that shows
# time info and beeps after said thing is done
# and nice and ionice for niceness
${VV_PRE} "$@"
# indicate we moved on to sync
echo "now syncing"
# and time the sync so we know how much the kernel was hiding from us
time sync
#beeper
}

vvr $@
alertr
